/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "ammt-bill": { "text": "Amount Billable:", "view": "DC.Text" },
    "done": { "creationFunction": "CreateGlassButton", "onclick": "saveSettingsAndFlip", "text": "Done" },
    "glassButton": { "creationFunction": "CreateGlassButton", "text": "Clock In" },
    "glassButton1": { "creationFunction": "CreateGlassButton", "text": "Clock Out" },
    "how-to": { "text": "Login to your Kokugen account here. Put your server ID in to connect. Good luck.", "view": "DC.Text" },
    "image": { "view": "DC.ImageLayout" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack" },
    "k-logo": { "view": "DC.ImageLayout" },
    "message-area": { "view": "DC.Text" },
    "ninec-logo": { "view": "DC.ImageLayout" },
    "open-close-btn": { "creationFunction": "CreateGlassButton", "text": "^" },
    "ovalShape": { "creationFunction": "CreateOvalShape" },
    "ovalShape1": { "creationFunction": "CreateOvalShape" },
    "ovalShape2": { "creationFunction": "CreateOvalShape" },
    "ovalShape3": { "creationFunction": "CreateOvalShape" },
    "pass-title": { "text": "Super Secret Password", "view": "DC.Text" },
    "plate": { "creationFunction": "CreateShape", "leftImageWidth": 5, "rightImageWidth": 5 },
    "rectangleShape": { "creationFunction": "CreateShape", "leftImageWidth": 2, "rightImageWidth": 2 },
    "serve-title": { "text": "Server", "view": "DC.Text" },
    "start-btn": { "creationFunction": "CreateButton", "disabled": true, "leftImageWidth": 5, "onclick": "startNewTask", "rightImageWidth": 5 },
    "stop-btn": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "stopTask", "rightImageWidth": 5 },
    "submit-btn": { "creationFunction": "CreateButton", "leftImageWidth": 5, "rightImageWidth": 5, "text": "Submit" },
    "Text": { "text": "Text", "view": "DC.Text" },
    "user-title": { "text": "Username", "view": "DC.Text" }
};






